server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/users/**, /auth/**

            - id: driverservice
              uri: lb://DRIVERSERVICE
              predicates:
                - Path=/drivers/**, /vehicles/**

            - id: tripservice
              uri: lb://TRIPSERVICE
              predicates:
                - Path=/trips/**


